  # Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "${HOSTNAME}:80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        networks:
            - app
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
#        image: php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        environment:
            PHP_IDE_CONFIG: "serverName=${DOCKER_GATEWAY}"
            XDEBUG_CONFIG:  "remote_host=${DOCKER_GATEWAY}"
        networks:
            - app
    mysql:
        image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/Http/mysql
        networks:
            - app
networks:
  app:
    driver: bridge
    ipam:
     config:
       - subnet: ${DOCKER_SUBNET}
         gateway: ${DOCKER_GATEWAY}